package ve.environment;

import javafx.scene.*;
import javafx.scene.paint.*;
import javafx.scene.shape.*;

import java.util.ArrayList;
import java.util.List;

public class E {//<-Static content for the game-environment stored here

 public static final AmbientLight ambientLight = new AmbientLight();
 public static final PointLight sunlight = new PointLight();
 public static final PointLight[] lightningLight = new PointLight[2];
 public static final PointLight mapViewerLight = new PointLight();
 public static final Sphere sun = new Sphere(200000000);
 public static final Sphere stormCloud = new Sphere(200000);
 public static final PhongMaterial cloudPM = new PhongMaterial(), starPM = new PhongMaterial(), poolPM = new PhongMaterial();
 public static final MeshView lightningMesh = new MeshView();
 public static final List<GroundPlate> groundPlates = new ArrayList<>();
 public static final List<TornadoPart> tornadoParts = new ArrayList<>();
 public static final List<TsunamiPart> tsunamiParts = new ArrayList<>();
 public static final List<Fire> fires = new ArrayList<>();
 public static final List<Boulder> boulders = new ArrayList<>();
 public static final List<VolcanoRock> volcanoRocks = new ArrayList<>();
 public static final List<Meteor> meteors = new ArrayList<>();
 public static final List<Cloud> clouds = new ArrayList<>();
 public static final List<Mountain> mountains = new ArrayList<>();
 public static final List<Star> stars = new ArrayList<>();
 public static final List<Raindrop> raindrops = new ArrayList<>();
 public static final List<Snowball> snowballs = new ArrayList<>();
 public static final long groundSpecularPower = 4;
 public static final int splashQuantity = 384;
 public static MeshView volcanoMesh;
 public static boolean pointLightExists, poolExists, lightningExists, volcanoExists, sandstormExists, tornadoMovesFixpoints;
 public static double gravity;
 public static double groundLevel;
 public static double groundX;
 public static double groundY;
 public static double groundZ;
 public static double windX;
 public static double windZ;
 public static double wind;
 public static double tornadoMaxTravelDistance;
 public static double boulderMaxTravelDistance;
 public static double poolX;
 public static double poolZ;
 public static double poolDepth;
 public static double sunlightAngle;
 public static double sunX;
 public static double sunY;
 public static double sunZ;
 public static double sunlightX;
 public static double sunlightY;
 public static double sunlightZ;
 public static double sunRGBVariance = .5;
 public static double cloudWrapDistance;
 public static final double rainWrapDistance = 2000;
 public static double stormCloudY;
 public static double lightningZ;
 public static double lightningX;
 public static final double snowWrapDistance = 2000;
 public static double tsunamiX;
 public static double tsunamiZ;
 public static double tsunamiSpeedZ;
 public static double tsunamiSpeedX;
 public static final double volcanoBottomRadius = 53000;
 public static final double volcanoTopRadius = 3000;
 public static final double volcanoHeight = 50000;
 public static double volcanoZ;
 public static double volcanoX;
 public static double volcanoEruptionStage;
 public static double meteorSpeed;
 public static final double[] skyRGB = {1, 1, 1};
 public static final double[] groundRGB = new double[3];
 public static final double[] terrainRGB = new double[3];
 public static final double[] cloudProperties = new double[4];
 public static final Cylinder ground = new Cylinder();
 public static final Cylinder[] pool = new Cylinder[2];
 public static long lightningStrikeStage, tsunamiSpeed, tsunamiDirection, randomThunderSound;
 public static Color skyInverse = Color.color(0, 0, 0), groundInverse = Color.color(1, 1, 1);
}
